### ISSUE TITLE
Failed to parse Json Response

### ISSUE THREAD

**Issue by fredrickwampamba** [Olili2017/training-spectrum-expenditure-app#5]
I need help on parsing the Json response into java. then put it in the array list, and then attach the adapter to the recycler view and i set the layout manager.
The json sample is like that (A return of expenses and income, amd a status for a successful response)
`{
    "income": [
        {
            "id": "14",
            "name": "",
            "amount": "0.0000",
            "date": "06-04-2021"
        },
        {
            "id": "10",
            "name": "full mine entrepreneurs logistics limited",
            "amount": "10000.0000",
            "date": "03-04-2021"
        }
    ],
    "expense": [
        {
            "id": "14",
            "name": "",
            "amount": "0.0000",
            "date": "06-04-2021"
        },
        {
            "id": "1",
            "name": "full mine entrepreneurs logistics limited",
            "amount": "10000.0000",
            "date": "03-04-2021"
        }
    ],
    "status": true
}`

Below is the code for java
`package com.ugnext.training.expenditureapp;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;
import android.widget.Toast;

import com.android.volley.Request;
import com.android.volley.RequestQueue;
import com.android.volley.Response;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonObjectRequest;
import com.android.volley.toolbox.StringRequest;
import com.android.volley.toolbox.Volley;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.Iterator;

public class TransactionsActivity extends AppCompatActivity {
    private static final String URL = "http://192.168.1.102/android/fetch.php";
    private ArrayList<TransactionsClass> transactionsClassArrayList;
    private TransactionsAdapter transactionsAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_transactions);

        RecyclerView recyclerView = findViewById(R.id.recyclerview);
        transactionsClassArrayList = new ArrayList<>();

//        transactionsAdapter.setTransactions(transactionsClassArrayList);
//        recyclerView.setAdapter(transactionsAdapter);

    }

    @Override
    protected void onStart() {
        super.onStart();

        JsonObjectRequest jsonObjectRequest = new JsonObjectRequest(Request.Method.GET, URL,null, new Response.Listener<JSONObject>() {
            @Override
            public void onResponse(JSONObject response) {
                try {
                     //problem starts here
                    JSONArray jsonArray = new JSONArray(response.getJSONArray("income"));
                    //problem ends here
//                    Toast.makeText(TransactionsActivity.this, jsonArray.toString(), Toast.LENGTH_LONG).show();

                } catch (JSONException e) {
                    e.printStackTrace();
                }
            }
        }, new Response.ErrorListener() {
            @Override
            public void onErrorResponse(VolleyError error) {

            }
        });

        RequestQueue requestQueue = Volley.newRequestQueue(this);
        requestQueue.add(jsonObjectRequest);

    }
}`

**Comment by fredrickwampamba** [comment]
Rectified.

**Comment by Olili2017** [comment]
ooooh okay.. thats good.. i hadnt looked at the code yet... but I presume your issues was solvable with gjson lib

**Comment by fredrickwampamba** [comment]
Yes, I was able to sole the issue. I had help with someones quick eye, he helped me see the issue. The app is now up and running. I am going to add, update and delete functions to it
